### ISSUE TITLE
dart2js iron_localStorage

### ISSUE THREAD

**Issue by terrywarwar** [dart-lang/polymer_elements#108]
When I run pub build, I get the following error.  iron_localStorage works fine during development.
[Error from Dart2JS on cpl_ami|web/index.bootstrap.initialize.dart]:
packages/cpl_ami/elements.dart:30:8:
Can't read 'package:polymer_elements/iron_localStorage.dart' (Could not find asset polymer_elements|lib/iron_localStorage.dart.).
export 'package:polymer_elements/iron_localStorage.dart';

**Comment by jakemac53** [comment]
it should be `package:polymer_elements/iron_localstorage.dart` (no camelCase)

**Comment by terrywarwar** [comment]
Thanks.
