### ISSUE TITLE
paper-item in paper-menu require two clicks to fire iron-activate in Firefox in rc6

### ISSUE THREAD

**Issue by alextekartik** [dart-lang/polymer_elements#117]
After upgrading from rc5 to rc6, I seem to have an issue already reported in polymer js but 6 months ago so I don't know if it is related (https://github.com/PolymerElements/paper-menu/issues/31)

Basically with 1.0.0rc5, paper-item in paper-menu in a drawer panel was working fine on firefox. However now with 1.0.0rc6:
- I need to click twice (does not have to be a double-click) on a paper-item to receive "iron-activate"
- on touch screen however tapping with a finger on it is fine

**Comment by jakemac53** [comment]
Looks like its an ongoing issue with the latest elements, I added another comment there to see if we can get some traction.

**Comment by zoechi** [comment]
Just saw an update a few minutes ago on an issue being fixed for a JS elements, don't remember details.

**Comment by jakemac53** [comment]
This is now fixed
