### ISSUE TITLE
iron-flex-layout not working

### ISSUE THREAD

**Issue by terrywarwar** [dart-lang/polymer_elements#119]
iron-flex-layout is no longer working with:

```
polymer: ^1.0.0-rc.14
polymer_elements: ^1.0.0-rc.7
web_components: ^0.12.2+2
```

```
 <div class="horizontal layout">
        <div>Alpha</div>
        <div class="flex">Beta (flex)</div>
        <div>Gamma</div>
 </div>
```

**Comment by jakemac53** [comment]
You need to import the stylesheet explicitly, I think it was previously included in one of the polymer elements so you were getting it transitively. See http://stackoverflow.com/questions/34756549/polymer-elements-1-0-0-rc-6-convert-horizontal-layout-to-vertical-layout/34774070#34774070.

**Comment by terrywarwar** [comment]
Thanks worked, changed from
`export 'package:polymer_elements/iron_flex_layout.dart';` 
to
`export 'package:polymer_elements/iron_flex_layout/classes/iron_flex_layout.dart';`
