### ISSUE TITLE
Impossible to use maps, social ... icons

### ISSUE THREAD

**Issue by lejard-h** [dart-lang/polymer_elements#122]
https://design.google.com/icons/

```
import 'package:polymer_elements/maps_icons.dart';
import 'package:polymer_elements/social_icons.dart';

// working
<paper-icon-button icon="card-membership"></paper-icon-button> 

// not working
<paper-icon-button icon="local-mall"></paper-icon-button>
<paper-icon-button icon="share"></paper-icon-button>

```

I am trying to use material icons.
All icons comming from the "action" pack are working.

But other pack like "maps", "social" does not seem to work, and I have no error.

I am using `polymer_elements 1.0.0-rc.8` and `polymer 1.0.0-rc.15`

**Comment by zoechi** [comment]
AFAIR you need to add the iconset id

```
<paper-icon-button icon="maps:local-mall"></paper-icon-button>
<paper-icon-button icon="social:share"></paper-icon-button>
```

**Comment by jakemac53** [comment]
@lejard-h can you confirm they work if you add the iconset id?

**Comment by lejard-h** [comment]
Oh yes thanks. Is It explain somewhere ?

**Comment by jakemac53** [comment]
https://elements.polymer-project.org/elements/iron-icons
