### ISSUE TITLE
Paper drop down content shrinks each time you use it

### ISSUE THREAD

**Issue by alextekartik** [dart-lang/polymer_elements#124]
(polymer element 1.0.0rc 8)

To reproduce, copy the following html in any element (no code needed - this is the code from the demo)

```
<paper-dropdown-menu label="Dinosaurs">
  <paper-listbox class="dropdown-content">
    <paper-item>allosaurus</paper-item>
    <paper-item>brontosaurus</paper-item>
    <paper-item>carcharodontosaurus</paper-item>
    <paper-item>diplodocus</paper-item>
  </paper-listbox>
</paper-dropdown-menu>
```

Each time I click on the arrow, the paper drown srinks until it becomes unusable.

someone reported that for the javascript version at some point: http://stackoverflow.com/questions/33639892/polymer-paper-dropdown-menu-button-shrinking

Any workaround available?

**Comment by zoechi** [comment]
That's a Dartium issue and shouldn't occur in other browsers.. A new Dartium is on its way (hopefully soon).

**Comment by alextekartik** [comment]
Indeed, I just checked on Chrome 48 and it works so that's fine. I'll close this issue. thanks Gunter

**Comment by cduzan** [comment]
I'm running into this same issue in Chrome (I have the latest version). However, it appears to be working fine in Firefox. Is anyone else running into this issue or can tell me what I'm doing wrong?
