### ISSUE TITLE
Unable to upgrade to polymer_elements 1.0.0-rc.9

### ISSUE THREAD

**Issue by emandere** [dart-lang/polymer_elements#141]
I get the following error when I try to upgrade to 1.0.0-rc.9

Resolving dependencies...
> polymer_elements 1.0.0-rc.9 (was 1.0.0-rc.8)
Error on line 198, column 1 of ..\..\..\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\polymer_elements-1.0.0-rc.9\pubspec.yaml: Duplicate mapping key.
environment:
^^^^^^^^^^^
Process finished with exit code 65

This started happening when I took the latest version of dart 1.23. Not sure if that is a contributing factor

**Comment by rillomas** [comment]
I'm getting this issue too.
I believe [this pull request](https://github.com/dart-lang/polymer_elements/pull/139/commits/8fd190c2d3948fc47a5039de289ebdad88b5436f#diff-fb2d52cd953afedcafc9fe7629c6f132) fixes it, but the pull request has been sitting there for a couple months already and I'm starting to get worried if it will ever get merged.

**Comment by jakemac53** [comment]
This should be resolved now, please re-open if it is not
