### ISSUE TITLE
Port remaining icon sets

### ISSUE THREAD

**Issue by ErikGrimes** [dart-lang/polymer_elements#27]
There are some additional icon sets in the iron-icons repo.
- av-icons
- communication-icons
- device-icons
- editor-icons
- hardware-icons
- image-icons
- maps-icons
- social-icons
- update-icons

**Comment by jakemac53** [comment]
resolved by https://github.com/dart-lang/polymer_elements/commit/78377ec059daebc6a61db1ca9196f6fec3cb2aea
