### ISSUE TITLE
paper_icon_button_basic_test 'applies an icon specified by the `icon` attribute' failing

### ISSUE THREAD

**Issue by ErikGrimes** [dart-lang/polymer_elements#31]
You can use the element in a polymer web app project and see the svg in the dom and query it via a querySelector.  The test below, however, fails.

```
expect(Polymer.dom(b1.$['icon'].jsElement['root']).querySelector('svg'),
          isNotNull);
```

**Comment by jakemac53** [comment]
passes now, probably due to polymer update
