### ISSUE TITLE
xp parameter for down helper should be optional

### ISSUE THREAD

**Issue by ErikGrimes** [dart-lang/polymer_elements#40]
A number of the paper-radio-button tests call the down helper to click the button without the xy parameter.  Making it optional and just passing null to the js method doesn't appear to work (the button doesn't get clicked), so creating this issue for now.

**Comment by vsheyanov** [comment]
@ErikGrimes hi, have you tried modifying down method to:

``` dart
void down(Node node, {Point xy: null}) {
  _MockInteractionsJs.callMethod('down', [node, xy == null ? null : xy.toJsObject()]);
}
```

**Comment by vsheyanov** [comment]
Actually it didn't work for me neither.

It's interesting that `down` method is used but not `tap`.

None of elements (paper-radio, paper-toggle-button) seems to switch state after clicking down...

**Comment by jakemac53** [comment]
Imo, if `tap` works its worth just changing the dart test to use that. You could add a comment like:

``` dart
// **Dart Note**: Using `tap` instead of `down` to get test to pass.
```

**Comment by jakemac53** [comment]
Confirmed, at least for paper-radio-button that `tap` is the correct action. It does not change state on a press down. 

I am making `xy` optional for both `down` and `up` though anyways.

**Comment by jakemac53** [comment]
fixed in https://github.com/dart-lang/polymer_elements/commit/37e2c8daea9018cb5e8b18d2b048b6683d08e39d
