### ISSUE TITLE
paper toggle button tests failing

### ISSUE THREAD

**Issue by vsheyanov** [dart-lang/polymer_elements#47]
~~1) `down` method is used that seems not to be switching element state~~
2) all tests are checking `aria-checked` attribute but examples on main polymer website seems to be modifiying `aria-pressed` attribute

**Comment by jakemac53** [comment]
Looks like [aria-pressed](http://www.w3.org/TR/wai-aria/states_and_properties#aria-pressed) is the correct attribute for a toggle button. We should probably just update the tests to check that attribute, and submit an issue to the original repo to fix their tests.

> Operating systems support pressed on buttons and checked on checkboxes

**Comment by vsheyanov** [comment]
Looks like this was already done:
https://github.com/PolymerElements/paper-toggle-button/issues/21

**Comment by vsheyanov** [comment]
I've added paper-toggle-button in polymer dart 1.0 project and when disabled it doesn't change neither checked value nor aria-pressed attribute.

Is it possible that `mock.tap` is not working properly in some way?

**Comment by jakemac53** [comment]
Hmm, it seems to be working in other contexts just fine so I don't think that's the issue? If you want to leave this marked as skipped for now I can investigate a little bit later.

**Comment by jakemac53** [comment]
This is fixed with the element update in the `update` branch.
