### ISSUE TITLE
Port the neon element tests!

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/polymer_elements#5]
Part of https://github.com/dart-lang/polymer_elements/issues/1.

**Comment by ErikGrimes** [comment]
There is only one test I could find for the neon elements, it is for neon-animated-pages.  The test relies on Polymer behaviors, so this would appear to be blocked on dart-lang/polymer-dart#551.

**Comment by ErikGrimes** [comment]
I actually ported the test, but it currently fails.  Do you want to pull anyway?

**Comment by jakemac53** [comment]
Yes lets pull it in, just mark it as `skip` for now and link the message to a github issue.

**Comment by jakemac53** [comment]
closed by https://github.com/dart-lang/polymer_elements/pull/22
