### ISSUE TITLE
iron-list doesn't work

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer_elements#57]
I tried `iron-list` but it doesn't render any items.
https://github.com/bwu-dart-playground/polymer1/blob/master/iron_list/web/app_element.html#L19

No idea if you're already interested on bug reports about these elements :confused:

**Comment by jakemac53** [comment]
This is just because your import to iron-list is commented out ;) https://github.com/bwu-dart-playground/polymer1/blob/697db655b1d87d25b9c01982866194cd60040592/iron_list/web/app_element.dart#L7

**Comment by jakemac53** [comment]
fwiw though yes I am interested in bug reports for these elements, we have ported the tests from JS but the coverage isn't great.

**Comment by zoechi** [comment]
Now I feel stupid :D
Thanks a lot! It seems I stopped seeing the wood because of all the trees.

I would like to build more examples to update my knowledge of Polymer and the elements. 
Anything I can contribute?

**Comment by jakemac53** [comment]
@damondouglas is working on porting the polymer-dart-patterns repo in [this pr](https://github.com/dart-lang/polymer-dart-patterns/pull/33), and you could probably coordinate with him and help with that.

Also I have not ported the polymer element demos at all yet. I wasn't really planning on doing it right away, but if you wanted to work on that it would be helpful as well.

**Comment by damondouglas** [comment]
@zoechi , would you like to experiment doing some live coding together maybe? It would be an honor to work with you on this.

**Comment by zoechi** [comment]
I was wondering how you plan to get the element demos ported. Did you port them all manually previously? 
@damondouglas sure. What timezone are you in, what are your working hours? I'm usually available from 6:00 AM GMT to 6:00 PM

**Comment by jakemac53** [comment]
@zoechi It has always been a manual process in the past, same for the tests. It would be pretty hard to do anything automatic unfortunately.
