### ISSUE TITLE
First login parameter should be Map

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer_elements#59]
https://github.com/dart-lang/polymer_elements/blob/d086c20f34ef784c746ee35d4e011abced08ad3d/lib/firebase_auth.dart#L102

Here https://github.com/GoogleWebComponents/firebase-element/blob/master/demo/x-login.html#L113 a map (object) with username and password is created and passed to the login method

**Comment by jakemac53** [comment]
https://github.com/GoogleWebComponents/firebase-element/pull/71

**Comment by zoechi** [comment]
Great, should be able to do that myself the next time :)

**Comment by jakemac53** [comment]
:) still have to regen the wrappers as well

**Comment by jakemac53** [comment]
fixed in the upcoming version

**Comment by zoechi** [comment]
This works now `_firebaseLogin.login(convertToJs(parameters), null);`
Is this supposed to work without `convertToJs()`?
Shouldn't this be `convertToJS()` anyway? (dart-lang/sdk#24624)

**Comment by jakemac53** [comment]
See https://github.com/dart-lang/custom-element-apigen/issues/2
