### ISSUE TITLE
gold-cc-cvc-input can't load image files

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer_elements#64]
`pub serve` prints

> [web] GET gold_cc_cvc_input/cvc_hint.png => Could not find asset polymer_elements_examples|web/gold_cc_cvc_input/cvc_hint.png.
> [web] GET gold_cc_cvc_input/cvc_hint_amex.png => Could not find asset polymer_elements_examples|web/gold_cc_cvc_input/cvc_hint_amex.png.

similar in the browser

> index.html:1 GET http://localhost:63342/polymer_elements/demo/web/gold_cc_cvc_input/cvc_hint.png 404 (Not Found)
> 2015-09-25 13:58:08.022index.html:1 GET http://localhost:63342/polymer_elements/demo/web/gold_cc_cvc_input/cvc_hint_amex.png 404 (Not Found)

The images are 
- http://localhost:63342/polymer_elements/demo/web/packages/polymer_elements/src/gold-cc-cvc-input/cvc_hint.png
- http://localhost:63342/polymer_elements/demo/web/packages/polymer_elements/src/gold-cc-cvc-input/cvc_hint_amex.png

Might be a Polymer issue instead a polymer_elements issue.

**Comment by jakemac53** [comment]
looks like an import inlining issue

**Comment by zoechi** [comment]
works fine now
