### ISSUE TITLE
The ga-api-utils element doesn't contain the required script file `ga-api-utils.js`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer_elements#65]
https://github.com/googleanalytics/javascript-api-utils/blob/master/build/ga-api-utils.js (referenced for example by https://github.com/GoogleWebComponents/google-analytics/blob/master/account-summaries-import.html)

**Comment by jakemac53** [comment]
ah crap, its in a `build` folder so its probably a bad .gitignore

**Comment by jakemac53** [comment]
fixed in the upcoming version
