### ISSUE TITLE
`<google-chart>` doesn't work with data and options (JSON) set in markup

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer_elements#66]
The `<google-chart>` component doesn't shown anything for elements where JSON is assigned to the `data` and `options` attributes in markup like

``` html
    <google-chart
      type="table"
      options='{"title": "Inventory"}'
      data='[["Year", "Things", "Stuff"],
             ["2004", 1000, 400],
             ["2005", 1170, 460],
             ["2006", 660, 1120],
             ["2007", 1030, 540]]'>
    </google-chart>
```

See 
https://github.com/GoogleWebComponents/google-chart/blob/master/demo/index.html for the full list of examples.
Two of the examples which load data from files instead from markup are working fine.

**Comment by zoechi** [comment]
This doesn't seem to be an issue anymore.

**Comment by jakemac53** [comment]
great!
