### ISSUE TITLE
How to pass a callback to IronA11yKeysBehavior?

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer_elements#70]
```
  ready() {
    var bindings = {
      '* pageup pagedown left right down up shift+a alt+a home end space enter':
          'updatePressed' // <<=== its passed as string in JS, how to do this from Dart?
    };
    keyBindings = bindings;
    set('boundKeys', bindings.keys.join(' ').split(' '));
  }

  @eventHandler
  void updatePressed(dom.CustomEvent event, [_]) { // <<=== isn't called
    print(event.detail);

    _pressed = '${pressed}${event.detail.combo} pressed!\n';
  }
```

I don't get any error, `updatePressed` just isn't called

**Comment by jakemac53** [comment]
Looks like in the test we are calling `addOwnKeyBinding`, which works but is not quite as nice maybe as setting up a static `keyBindings` property. The other alternative would be to set the `keyBindings` object on the prototype of an element/behavior, but that would be pretty cumbersome to do by hand compared to just calling `addOwnKeyBinding`.

We probably should add nice a way of adding arbitrary properties to the js prototypes though, which would be similar to @eventHandler but for properties. This would need to support statics as well (keyBindings for instance would be static most likely).

**Comment by zoechi** [comment]
Seems I don't understand the problem nor the solution :-/
`addOwnKeyBinding` also passes the event handler name as string.
`keyBindings` is a getter/setter of `IronA11yKeysBehavior` (just to be sure you didn't misinterpret it in my code)

**Comment by jakemac53** [comment]
Basically the element shouldn't really have a `keyBindings` setter most likely. That property is only read when the element is registered, so setting it in ready has no effect. Calling `addOwnKeyBinding` is the imperative post-registration way of doing the same thing.

**Comment by zoechi** [comment]
Ok, I think now I got it :)
