### ISSUE TITLE
`attached` from IronFormElementBehavior not called

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer_elements#72]
I have the following element

``` dart
@PolymerRegister('simple-element', extendsTag: 'input')
class SimpleElement extends dom.InputElement
    with PolymerMixin, PolymerBase, JsProxy, IronFormElementBehavior {
  SimpleElement.created() : super.created() {
    polymerCreated();
  }
}
```

`IronFormElementBehavior` fires  `'iron-form-element-register'` in `attached` but with my element this event isn't fired.

(see also https://github.com/PolymerElements/iron-form-element-behavior/blob/master/demo/simple-form.html#L28)

**Comment by jakemac53** [comment]
Question: if you do `querySelector('simple-element').jsElement['behaviors']` do you see the `Polymer.IronFormElementBehavior` in the list?

**Comment by zoechi** [comment]
~~`jsElement` is `undefined`.~~

**Comment by zoechi** [comment]
Sorry, was my mistake.
It contains `InteropBehavior` (`notifyPath`, `serialize`) and `IronFormElementBehavior` (`attached`, `detached`, `properties`)

**Comment by jakemac53** [comment]
Ok so Polymer Dart looks like its doing the right thing then. You could try setting a breakpoint inside the attached method of the IronFormElementBehavior to check whether it is actually being called?

**Comment by zoechi** [comment]
If you're talking about the Dart class `IronFormElementBehavior` then it might be the problem that there is no `attached` method.
https://github.com/dart-lang/polymer_elements/blob/master/lib/iron_form_element_behavior.dart

**Comment by jakemac53** [comment]
I actually mean the JS definition of the behavior, which is here https://github.com/dart-lang/polymer_elements/blob/593a6a30e40584ae672b26174e372c16127d5a18/lib/src/iron-form-element-behavior/iron-form-element-behavior.html#L75. The lifecycle methods are intentionally not included in the dart mixins, since they aren't meant to be invoked directly.

**Comment by zoechi** [comment]
Actually it's called 
`this.fire('iron-form-element-register');` is executed.
I'll investigate further why the event isn't received...

**Comment by zoechi** [comment]
Damit, I forgot `polymerCreated();` in the constructor in one of the two elements.
Sorry  :-(

**Comment by jakemac53** [comment]
np, glad you figured it out!
