### ISSUE TITLE
iron_range_behavior throws when a numeric property returns a string

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer_elements#74]
Dart
https://github.com/dart-lang/polymer_elements/blob/3b7cdde2226e8e5f9076a0e483ecd75f1266d058/lib/iron_range_behavior.dart#L33

JS
https://github.com/PolymerElements/iron-range-behavior/blob/master/iron-range-behavior.html#L29

The actual value I got was `"5"` which can be converted to `num`.

**Comment by jakemac53** [comment]
Seems like a bug in the original element, it should be a num as it claims it is.

**Comment by zoechi** [comment]
I didn't expect types in JS are to be trusted. I'll create a bug report there then.

**Comment by jakemac53** [comment]
These wrappers do trust the types. This causes issues like this one sometimes but really its just revealing a bug in the original element so I think that is ok.

**Comment by jakemac53** [comment]
re-opening here until it gets fixed on the js side (and then migrated here)

**Comment by jakemac53** [comment]
also filed https://github.com/dart-lang/custom-element-apigen/issues/41

**Comment by jakemac53** [comment]
fixed in upcoming version
