### ISSUE TITLE
platinum-*.html missing in `lib/src/`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer_elements#75]
https://github.com/dart-lang/polymer_elements/blob/master/lib/platinum_push_messaging_nodart.html#L1
`<link rel="import" href="src/platinum-push-messaging/platinum-push-messaging.html">`

**Comment by jakemac53** [comment]
Oh, these are actually not supported (at least today) and were removed from lib/src, but I forgot to remove the wrappers.
