### ISSUE TITLE
Missing IconSelectableBehavior mixin from PaperMenu

### ISSUE THREAD

**Issue by alextekartik** [dart-lang/polymer_elements#77]
The following works fine

``` dart
print('selected: ${menu.jsElement[r'selected']}');
```

while this

``` dart
print('selected: ${menu.selected}');
```

causes

```
Exception: Class 'PaperMenu' has no instance getter 'selected'.

NoSuchMethodError: method not found: 'selected'
Receiver: Instance of 'PaperMenu'
Arguments: []
```

It seems that PaperMenu is missing "with IronSelectableBehavior".
The root cause is that IronMultiSelectableBehavior is supposed to implement "IronSelectableBehavior" which is not the case (I guess that's our current mixin limitation).

**Comment by zoechi** [comment]
`IronMultiSelectableBehavior` only `implements IronSelectableBehavior` (a mixin can't extend another class)
therefore `PaperMenu` needs a `with IronSelectableBehavior` itself to actually get an implementation.
DartAnalyzer for `PaperMenu` shows `..., missing concrete implementation of getter IronSelectableBehavior.selected ...` but the noisy "unused imports" make them hard to find.

**Comment by zoechi** [comment]
> (a mixin can't extend another class)

this limitation is about to vanish :smile: https://github.com/dart-lang/sdk/issues/23770

**Comment by zoechi** [comment]
The `IronSelectableBehavior` is still missing in the update branch.
