### ISSUE TITLE
Incompatible version constraints on reflectable with polymer 1.0.0-rc.2

### ISSUE THREAD

**Issue by terrywarwar** [dart-lang/polymer_elements#78]
Incompatible version constraints on reflectable:
- polymer 1.0.0-rc.2 depends on version ^0.3.1
- polymer_elements 0.1.0 depends on version ^0.2.0

**Comment by zoechi** [comment]
Just add dependency_overrides

**Comment by terrywarwar** [comment]
Thanks, that did the trick.

**Comment by jakemac53** [comment]
fwiw I did just update polymer_elements to the newest polymer version and upgraded the reflectable dependency as well

**Comment by zoechi** [comment]
Great! 
Any plans to regenerate the wrappers?  It seems there were a lot of fixes added to the JS elements not yet available in Dart?

**Comment by jakemac53** [comment]
Yes, I do need to get around to that eventually, I have just been very busy polishing other things ;)
