### ISSUE TITLE
Some workaround to get rid of of "Unused import" hints

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer_elements#88]
The high number of "Unused imports" hints renders the "Dart Analysis" window in WebStorm useless. It is already of limited value without these "Unused imports" hints because it updates automatically and any selections, scrolling, expand/collapse are lost every few seconds. There are open issues to improve it though but doesn't seem to have priority.

What about adding a member like `const silentImportElementName = 0; in every elements Dart file and adding a a doc-comment in the importing file like`/// silentImportElementName]` where no member of the imported library is used?

**Comment by jakemac53** [comment]
I really would like to avoid adding actual code to get rid of analysis warnings, even if dart2js would be able to easily remove them in the deployed app.

The `custom-element-apigen` generator doesn't use the analyzer at all or do any resolution, so it doesn't know what it is or is not actually using, so that makes solving this problem difficult.

I agree this is annoying though.

**Comment by zoechi** [comment]
I didn't assume that the analyzer is used but I assumed that the script usually should know what it adds the import for. If it is just for the HTML it should add it to the doc comment. I did something similar for generating the stubs for the demos. If it's too complicated than it's probably better to leave it as it is and wait for the analyzer to provide a solution.

**Comment by jakemac53** [comment]
The way it actually works is just by looking at the original html imports, it just converts those all to dart imports. There is some global knowledge though of what imports contain what classes/etc, so it could be smarter.

**Comment by zoechi** [comment]
Getting rid of half the hints would already be a notable improvement.

**Comment by zoechi** [comment]
I guess this dart-lang/sdk#25685 (already landed in BE) will solve this.
