### ISSUE TITLE
neon-animated-pages entry and exit animations not found

### ISSUE THREAD

**Issue by ErikGrimes** [dart-lang/polymer_elements#89]
The warning shows up in the JavaScript console log.

**Comment by ErikGrimes** [comment]
Closing.  Didn't realize they needed to be imported separately.

**Comment by zoechi** [comment]
I didn't investigate much yet but I saw that in JS there is a neon-animations.html which imports all animations at once, I couldn't find such a file in Dart (didn't check after the last update)
