### ISSUE TITLE
PaperCheckedElementBehavior from PaperBehaviors is missing

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer_elements#96]
added recently. 

How should this JS be ported to Dart?
https://github.com/PolymerElements/paper-behaviors/blob/7a674a3635fcb6db4842d16d3fd768ab07d638a8/demo/paper-radio-button.html#L113

**Comment by jakemac53** [comment]
Added in the new version - luckily we don't have to port that one part to dart ;). In general though that sort of problem could be solved by enabling super calls in mixins.
